name: my_tests
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  country_code_picker: ^3.0.0
  google_sign_in: ^6.2.2 # تأكد من استخدام أحدث إصدار
  sqflite: ^2.0.0+3
  path: ^1.8.0
  firebase_app_check: ^0.3.1+7

  syncfusion_flutter_charts: ^27.1.51
  table_calendar: ^3.0.0
  http: ^1.1.2
  text_analysis: ^1.0.0
  cupertino_icons: ^1.0.6
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.1.2
  flutter_gemini: ^2.0.4
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profilePersonaly.png
